
// Code generated by Fabrica dev. DO NOT EDIT.
// Template: init/main.go.tmpl
// Generated: 2026-02-03T14:24:34-08:00
//
// Copyright © 2025 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT

package main

import (
	"context"
	"fmt"
	"log"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/spf13/cobra"
	"github.com/spf13/viper"
	"github.com/go-chi/chi/v5"
	"github.com/go-chi/chi/v5/middleware"

	

	

	 "github.com/OpenCHAMI/node-service/internal/storage"
	
	

	
	"github.com/openchami/fabrica/pkg/events"
	. "github.com/OpenCHAMI/node-service/internal/middleware"
	

	
	"github.com/openchami/fabrica/pkg/reconcile"
	"github.com/OpenCHAMI/node-service/pkg/reconcilers"
	
)

// Config holds all configuration for the service
type Config struct {
	// Server Configuration
	Port         int    `mapstructure:"port"`
	Host         string `mapstructure:"host"`
	ReadTimeout  int    `mapstructure:"read_timeout"`
	WriteTimeout int    `mapstructure:"write_timeout"`
	IdleTimeout  int    `mapstructure:"idle_timeout"`

	
	// Storage Configuration
	
	DataDir string `mapstructure:"data_dir"`
	
	

	

	
	// Reconciliation Configuration
	ReconcileEnabled bool `mapstructure:"reconcile_enabled"`
	ReconcileWorkers int  `mapstructure:"reconcile_workers"`
	

	// Feature Flags
	
	Debug bool `mapstructure:"debug"`
}

// DefaultConfig returns the default configuration
func DefaultConfig() *Config {
	return &Config{
		Port:         8080,
		Host:         "0.0.0.0",
		ReadTimeout:  15,
		WriteTimeout: 15,
		IdleTimeout:  60,
		
		
		DataDir:      "./data",
		
		
		
		
		ReconcileEnabled: true,
		ReconcileWorkers: 5,
		
		
		Debug: false,
	}
}

var (
	cfgFile string
	config  *Config
)

func main() {
	if err := rootCmd.Execute(); err != nil {
		log.Fatal(err)
	}
}

var rootCmd = &cobra.Command{
	Use:   "node-service-2",
	Short: "",
	Long:  `node-service-2 - A Fabrica-generated OpenCHAMI service`,
	RunE:  runServer,
}

var serveCmd = &cobra.Command{
	Use:   "serve",
	Short: "Start the node-service-2 server",
	Long:  `Start the node-service-2 HTTP server with the configured options`,
	RunE:  runServer,
}

func init() {
	cobra.OnInitialize(initConfig)

	// Global flags
	rootCmd.PersistentFlags().StringVar(&cfgFile, "config", "", "config file (default is $HOME/.node-service-2.yaml)")
	rootCmd.PersistentFlags().Bool("debug", false, "Enable debug logging")

	// Server flags
	serveCmd.Flags().IntP("port", "p", 8080, "Port to listen on")
	serveCmd.Flags().String("host", "0.0.0.0", "Host to bind to")
	serveCmd.Flags().Int("read-timeout", 15, "Read timeout in seconds")
	serveCmd.Flags().Int("write-timeout", 15, "Write timeout in seconds")
	serveCmd.Flags().Int("idle-timeout", 60, "Idle timeout in seconds")

	
	
	serveCmd.Flags().String("data-dir", "./data", "Directory for file storage")
	
	

	

	

	// Bind flags to viper
	viper.BindPFlags(serveCmd.Flags())
	viper.BindPFlags(rootCmd.PersistentFlags())

	// Add subcommands
	rootCmd.AddCommand(serveCmd)
	
	rootCmd.AddCommand(versionCmd)
	
}

func initConfig() {
	config = DefaultConfig()

	if cfgFile != "" {
		viper.SetConfigFile(cfgFile)
	} else {
		// Search for config in home directory
		home, err := os.UserHomeDir()
		cobra.CheckErr(err)

		viper.AddConfigPath(home)
		viper.AddConfigPath(".")
		viper.SetConfigType("yaml")
		viper.SetConfigName(".node-service-2")
	}

	// Environment variables
	viper.SetEnvPrefix("NODE-SERVICE-2")
	viper.AutomaticEnv()

	// Read config file if it exists
	if err := viper.ReadInConfig(); err == nil {
		log.Printf("Using config file: %s", viper.ConfigFileUsed())
	}

	// Unmarshal config
	if err := viper.Unmarshal(config); err != nil {
		log.Fatalf("Unable to decode into config struct: %v", err)
	}

	// Set debug logging
	if config.Debug {
		log.SetFlags(log.LstdFlags | log.Lshortfile)
		log.Println("Debug logging enabled")
	}
}

func runServer(cmd *cobra.Command, args []string) error {
	log.Printf("Starting node-service-2 server...")

	
	// Initialize storage backend
	
	if err := storage.InitFileBackend(config.DataDir); err != nil {
	  return fmt.Errorf("failed to initialize file storage: %w", err)
	}
	log.Printf("File storage initialized in %s", config.DataDir)
	
	

	
	// Initialize event system with configuration from environment
	eventConfig := &events.EventConfig{
		Enabled:                true,
		EventTypePrefix:        viper.GetString("event_type_prefix"),
		LifecycleEventsEnabled: viper.GetBool("lifecycle_events_enabled"),
		ConditionEventsEnabled: viper.GetBool("condition_events_enabled"),
	}

	// Use defaults if not configured
	if eventConfig.EventTypePrefix == "" {
		eventConfig.EventTypePrefix = "node-service-2.resource"
	}
	if !viper.IsSet("lifecycle_events_enabled") {
		eventConfig.LifecycleEventsEnabled = true
	}
	if !viper.IsSet("condition_events_enabled") {
		eventConfig.ConditionEventsEnabled = true
	}

	// Initialize event configuration
	events.SetEventConfig(eventConfig)

	// Initialize event bridge for condition events
	events.InitializeEventBridge()

	// Initialize event bus for handlers
	if err := InitializeEventBus(); err != nil {
		log.Fatalf("Failed to initialize event bus: %v", err)
	}

	log.Printf("Event system initialized - Lifecycle: %v, Conditions: %v, Prefix: %s",
		eventConfig.LifecycleEventsEnabled, eventConfig.ConditionEventsEnabled, eventConfig.EventTypePrefix)
	

	
	// Initialize reconciliation controller
	var controller *reconcile.Controller
	
	if config.ReconcileEnabled {
		ctx := context.Background()

		// Initialize event bus
		
		eventBus := events.NewInMemoryEventBus(100, 5)
		
		eventBus.Start()
		defer eventBus.Close()

		// Create reconciliation controller
		controller = reconcile.NewController(eventBus, storage.Backend)

		// Create storage client for reconcilers
		storageClient := storage.NewStorageClient()

		// Register reconcilers
		if err := reconcilers.RegisterReconcilers(controller, storageClient, eventBus); err != nil {
			log.Fatalf("Failed to register reconcilers: %v", err)
		}

		// Start controller
		if err := controller.Start(ctx); err != nil {
			log.Fatalf("Failed to start reconciliation controller: %v", err)
		}
		defer controller.Stop()

		log.Printf("Reconciliation controller started with %d workers", 5)
	}
	
	

	// Setup router
	r := chi.NewRouter()

	// Add middleware
	r.Use(middleware.Logger)
	r.Use(middleware.Recoverer)
	r.Use(middleware.RequestID)
	r.Use(middleware.RealIP)

	if config.Debug {
		r.Mount("/debug", middleware.Profiler())
	}

	

	// Register routes - generated by 'fabrica generate'
	RegisterGeneratedRoutes(r)
	r.Get("/health", healthHandler)

	

	// Create HTTP server
	addr := fmt.Sprintf("%s:%d", config.Host, config.Port)
	server := &http.Server{
		Addr:         addr,
		Handler:      r,
		ReadTimeout:  time.Duration(config.ReadTimeout) * time.Second,
		WriteTimeout: time.Duration(config.WriteTimeout) * time.Second,
		IdleTimeout:  time.Duration(config.IdleTimeout) * time.Second,
	}

	// Start server in goroutine
	go func() {
		log.Printf("Server starting on %s", addr)
		
		
		log.Printf("Storage: file backend in %s", config.DataDir)
		
		
		

		if err := server.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			log.Fatalf("Server failed: %v", err)
		}
	}()

	// Wait for interrupt signal for graceful shutdown
	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	<-quit
	log.Println("Server shutting down...")

	// Graceful shutdown with timeout
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	if err := server.Shutdown(ctx); err != nil {
		return fmt.Errorf("server forced to shutdown: %w", err)
	}

	log.Println("Server exited")
	return nil
}

// Health check handler
func healthHandler(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	w.Write([]byte(`{"status":"healthy","service":"node-service-2"}`))
}




var versionCmd = &cobra.Command{
	Use:   "version",
	Short: "Print the version number",
	Long:  `Print the version number of node-service-2`,
	Run: func(cmd *cobra.Command, args []string) {
		fmt.Println("node-service-2 v1.0.0")
	},
}

