// Code generated by Fabrica dev. DO NOT EDIT.
// Template: init/main.go.tmpl
// Generated: 2026-02-03T14:24:34-08:00
//
// Copyright © 2025 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT

package main

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/go-chi/chi/v5/middleware"
	"github.com/spf13/cobra"
	"github.com/spf13/viper"

	"github.com/OpenCHAMI/node-service/internal/storage"
	"github.com/OpenCHAMI/node-service/pkg/reconcilers"
	"github.com/openchami/fabrica/pkg/events"
	"github.com/openchami/fabrica/pkg/reconcile"
)

// Config holds all configuration for the service
type Config struct {
	Port             int    `mapstructure:"port"`
	Host             string `mapstructure:"host"`
	ReadTimeout      int    `mapstructure:"read_timeout"`
	WriteTimeout     int    `mapstructure:"write_timeout"`
	IdleTimeout      int    `mapstructure:"idle_timeout"`
	DataDir          string `mapstructure:"data_dir"`
	ReconcileEnabled bool   `mapstructure:"reconcile_enabled"`
	ReconcileWorkers int    `mapstructure:"reconcile_workers"`
	Debug            bool   `mapstructure:"debug"`
}

func DefaultConfig() *Config {
	return &Config{
		Port:             8080,
		Host:             "0.0.0.0",
		ReadTimeout:      15,
		WriteTimeout:     15,
		IdleTimeout:      60,
		DataDir:          "./data",
		ReconcileEnabled: true,
		ReconcileWorkers: 5,
		Debug:            false,
	}
}

var (
	cfgFile string
	config  *Config
)

func main() {
	if err := rootCmd.Execute(); err != nil {
		log.Fatal(err)
	}
}

var rootCmd = &cobra.Command{
	Use:   "node-service-2",
	Short: "",
	Long:  `node-service-2 - A Fabrica-generated OpenCHAMI service`,
	RunE:  runServer,
}

var serveCmd = &cobra.Command{
	Use:   "serve",
	Short: "Start the node-service-2 server",
	RunE:  runServer,
}

func init() {
	cobra.OnInitialize(initConfig)
	rootCmd.PersistentFlags().StringVar(&cfgFile, "config", "", "config file")
	rootCmd.PersistentFlags().Bool("debug", false, "Enable debug logging")

	serveCmd.Flags().IntP("port", "p", 8080, "Port to listen on")
	serveCmd.Flags().String("host", "0.0.0.0", "Host to bind to")
	serveCmd.Flags().String("data-dir", "./data", "Directory for file storage")

	viper.BindPFlags(serveCmd.Flags())
	viper.BindPFlags(rootCmd.PersistentFlags())
	rootCmd.AddCommand(serveCmd)
	rootCmd.AddCommand(versionCmd)
}

func initConfig() {
	config = DefaultConfig()
	if cfgFile != "" {
		viper.SetConfigFile(cfgFile)
	} else {
		home, _ := os.UserHomeDir()
		viper.AddConfigPath(home)
		viper.AddConfigPath(".")
		viper.SetConfigType("yaml")
		viper.SetConfigName(".node-service-2")
	}
	viper.SetEnvPrefix("NODE-SERVICE-2")
	viper.AutomaticEnv()
	if err := viper.ReadInConfig(); err == nil {
		log.Printf("Using config file: %s", viper.ConfigFileUsed())
	}
	viper.Unmarshal(config)
}

// Global reference for our manual setup
var ManualEventBus events.EventBus

func runServer(cmd *cobra.Command, args []string) error {
	log.Printf("Starting node-service-2 server...")

	// 1. Initialize Storage
	if err := storage.InitFileBackend(config.DataDir); err != nil {
		return fmt.Errorf("failed to initialize file storage: %w", err)
	}

	// 2. MANUAL EVENT BUS SETUP
	// We create one bus right here. It starts automatically on creation.
	ManualEventBus = events.NewInMemoryEventBus(100, 5)
	
	// Register it globally just in case
	events.SetGlobalEventBus(ManualEventBus)
	
	log.Printf("Manual Event Bus initialized.")

	// 3. Initialize Reconciliation
	if config.ReconcileEnabled {
		ctx := context.Background()

		// Debug Listener
		ManualEventBus.Subscribe(">", func(ctx context.Context, evt events.Event) error {
			log.Printf(">>> EVENT SNIFFER: Received [%s]", evt.Type)
			return nil
		})

		// Create Controller with OUR Manual Bus
		controller := reconcile.NewController(ManualEventBus, storage.Backend)
		storageClient := storage.NewStorageClient()

		// Register Reconcilers with OUR Manual Bus
		if err := reconcilers.RegisterReconcilers(controller, storageClient, ManualEventBus); err != nil {
			log.Fatalf("Failed to register reconcilers: %v", err)
		}

		if err := controller.Start(ctx); err != nil {
			log.Fatalf("Failed to start reconciliation controller: %v", err)
		}
		defer controller.Stop()
		log.Printf("Reconciliation controller started with %d workers", config.ReconcileWorkers)
	}

	// 4. Setup Router & Server
	r := chi.NewRouter()
	r.Use(middleware.Logger)
	r.Use(middleware.Recoverer)
	
	// FIX: Use our custom injector AND PASS THE BUS EXPLICITLY
	r.Use(EventInjectorMiddleware) 
	
	RegisterGeneratedRoutes(r)
	r.Get("/health", healthHandler)

	addr := fmt.Sprintf("%s:%d", config.Host, config.Port)
	server := &http.Server{Addr: addr, Handler: r}

	go func() {
		log.Printf("Server starting on %s", addr)
		if err := server.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			log.Fatalf("Server failed: %v", err)
		}
	}()

	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	<-quit
	
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	server.Shutdown(ctx)
	
	return nil
}

func healthHandler(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusOK)
	w.Write([]byte(`{"status":"healthy"}`))
}

var versionCmd = &cobra.Command{
	Use: "version",
	Run: func(cmd *cobra.Command, args []string) { fmt.Println("v1.0.0") },
}

// --- CUSTOM MIDDLEWARE ---

type responseBuffer struct {
	http.ResponseWriter
	body   *bytes.Buffer
	status int
}

func (w *responseBuffer) Write(b []byte) (int, error) {
	w.body.Write(b)
	return w.ResponseWriter.Write(b)
}

func (w *responseBuffer) WriteHeader(status int) {
	w.status = status
	w.ResponseWriter.WriteHeader(status)
}

func EventInjectorMiddleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Method != "POST" {
			next.ServeHTTP(w, r)
			return
		}

		buf := &bytes.Buffer{}
		wb := &responseBuffer{ResponseWriter: w, body: buf, status: 200}
		next.ServeHTTP(wb, r)

		if wb.status >= 200 && wb.status < 300 {
			resourceType := ""
			if r.URL.Path == "/nodes" { resourceType = "Node" }
			if r.URL.Path == "/nodesets" { resourceType = "NodeSet" }

			if resourceType != "" {
				var respData map[string]interface{}
				if err := json.Unmarshal(wb.body.Bytes(), &respData); err == nil {
					if meta, ok := respData["metadata"].(map[string]interface{}); ok {
						if uid, ok := meta["uid"].(string); ok {
							
							// MANUAL FIRE using the bus variable we control
							eventType := fmt.Sprintf("com.fabrica.%s.created", resourceType)
							evt, _ := events.NewEvent(eventType, "/api/"+resourceType, respData)
							
							ManualEventBus.Publish(context.Background(), *evt)
							
							log.Printf(">>> INJECTOR: Fired event for %s %s", resourceType, uid)
						}
					}
				}
			}
		}
	})
}